### PR TITLE
Add comment for future developers

### PR DESCRIPTION
**Pull request by cadenmyers13**

### CODE REVIEW

**Comment by cadenmyers13** [comment]
> **Warning!** No news item is found for this PR. If this is a user-facing change/feature/fix, please add a news item by copying the format from `news/TEMPLATE.rst`.

@sbillinge Would we want to create a news item for this? Thought maybe editing past news file would cause the check to pass lol...

**Review by sbillinge — COMMENTED** [review]
thanks @cadenmyers13 . We don't want a news for this one because there is already a news for this issue so it will be duplicated in the changelog.

Also, the commit messages are not up to standard and there appears to be multiple commits for a PR that just adds a one line comment.   

I will close this.  Could you do it over maybe?    

Also, I see a comment that says `# when`.  Is this providing the user useful information?  I doubt it.  

I would love it if we could try and raise our aspirations for code quality and take ownership of our projects, like our children that we want to be proud of.  It means loving the code a bit and always trying to think of ways to make it better.

**Comment by sbillinge** [comment]
Ah, further to my review comments, I see that the edits to the news were editing a previous news to make it better....so kudos for that!  Please ignore that part of my comments!

**Comment by cadenmyers13** [comment]
> thanks @cadenmyers13 . We don't want a news for this one because there is already a news for this issue so it will be duplicated in the changelog.
> 
> 
> 
> Also, the commit messages are not up to standard and there appears to be multiple commits for a PR that just adds a one line comment.   
> 
> 
> 
> I will close this.  Could you do it over maybe?    
> 
> 
> 
> Also, I see a comment that says `# when`.  Is this providing the user useful information?  I doubt it.  
> 
> 
> 
> I would love it if we could try and raise our aspirations for code quality and take ownership of our projects, like our children that we want to be proud of.  It means loving the code a bit and always trying to think of ways to make it better.

Got it! Will do. I made multiple commits because I was dissatisfied with wording (I was being indecisive). I can clean it up and make a new PR tomorrow.

**Comment by sbillinge** [comment]
In that case multiple commits are ok, but you need to commicate through the commit messages.  That is one reason (not the only one) why they are so important.  Also, when you write that commit message it helps you think before you commit and you may end up with less indecision....

**Pull request closed without merging**
