### PR TITLE
remove `.coveragerc` file

### LINKED ISSUE #57: Remove `.coveragerc` (no longer needed with our cookiecutter setup)
Please see https://github.com/Billingegroup/cookiecutter/pull/177#discussion_r1826404794

@cadenmyers13

### PR DESCRIPTION
**Pull request by cadenmyers13**
closes #57. With `tests` at top level, we no longer need to omit any files as `pytest` automatically detects files in `tests`. https://github.com/Billingegroup/cookiecutter/pull/177#discussion_r1826404794

### CODE REVIEW

**Comment by cadenmyers13** [comment]
This isn't passing after I made a second push, similar to the other PR here https://github.com/diffpy/diffpy.fourigui/pull/55

**Review by sbillinge — COMMENTED** [review]
This PR is better without a news.   Delete the news.

**Comment by sbillinge** [comment]
@cadenmyers13 also, this is failing tests.  Some issue with codecov

**Comment by cadenmyers13** [comment]
> codecov/codecov-action#1580

Yeah... there's a github thread here discussing it: https://github.com/codecov/codecov-action/issues/1580

**Comment by sbillinge** [comment]
Thanks @cadenmyers13 

Looks like the codecov problem is resolved too!

**Pull request merged**
