### PR TITLE
Remove bullet in README

### PR DESCRIPTION
**Pull request by cadenmyers13**
All other packages don't have a bullet point in the description, so i removed it. This should fix the PyPI rendering error.

### CODE REVIEW

**Comment by cadenmyers13** [comment]
Sorry for the multiple commits. Also, no news item.

**Comment by bobleesj** [comment]
Have you tried building locally? @cadenmyers13

**Comment by cadenmyers13** [comment]
> Have you tried building locally? @cadenmyers13

Yes, here's a ss

Screenshot 2024-11-11 at 1 36 28 PM

**Comment by bobleesj** [comment]
Sounds great.

**Pull request merged**
