### PR TITLE
Add tkinter and matplotlib to autodoc_mock_imports to render API Doc via Linux CI

### PR DESCRIPTION
**Pull request by bobleesj**
Screenshot 2024-12-09 at 6 13 30 PM

@sbillinge @cadenmyers13 Working now, using the same reusable workflow.

https://bobleesj.github.io/diffpy.fourigui/api/diffpy.fourigui.html

After merged, please deploy doc by workflow dispatch!

### CODE REVIEW

**Comment by bobleesj** [comment]
https://github.com/diffpy/diffpy.fourigui/blob/main/news/h5py.rst

No additional news is created since a news file has been created above.

**Comment by bobleesj** [comment]
@sbillinge https://github.com/diffpy/diffpy.fourigui/actions/workflows/publish-docs-on-release.yml

seems like github pages was deployed but the workflow wasn't

**Comment by sbillinge** [comment]
sorry, try again.   its 5 am here....not functioning at full capacity

**Comment by sbillinge** [comment]
still didn't build properly?  Not sure why.  Too hard to debug on little sleep and train wifi...

**Comment by bobleesj** [comment]
Screenshot 2024-12-10 at 9 42 28 AM

The workflow name is called `Deploy Documentation on Release` - could you pls run from this URL: https://github.com/diffpy/diffpy.fourigui/actions/workflows/publish-docs-on-release.yml ?

**Comment by bobleesj** [comment]
(I see that the last run was done 4 days ago for `Deploy Documentation on Release`)

**Pull request merged**
