### PR TITLE
Add headless to `true` to doc GitHub build workflow to `sudo apt-get install -y xvfb`

### PR DESCRIPTION
**Pull request by bobleesj**
The goal of this PR is to ensure we can render API doc strings with our linux CI. 

Closes https://github.com/diffpy/diffpy.fourigui/issues/70 - fixing API docstrings
Closes https://github.com/diffpy/diffpy.fourigui/issues/18 - build API doc
Closes https://github.com/diffpy/diffpy.fourigui/issues/33 - fixing doc link

### CODE REVIEW

**Comment by bobleesj** [comment]
@sbillinge ready for review 

@cadenmyers13 once this is merged, let's try to deploy the doc from your forked repo and let's see if this works!

**Comment by cadenmyers13** [comment]
@bobleesj I made the edits and the API rendered properly 👍  Just add a news item and this should be good to go once reviewed

Screenshot 2024-12-06 at 10 16 33 AM

**Comment by bobleesj** [comment]
> @bobleesj I made the edits and the API rendered properly 👍 Just add a news item and this should be good to go once reviewed

Beautiful!!! Time to finally wrap our release up.

**Comment by sbillinge** [comment]
Thanks @bobleesj !

**Comment by bobleesj** [comment]
@cadenmyers13 

@sbillinge deployed the docs by dispatch from `main` but it appears the API docs are not being rendered. 

The screenshot above indeed indicate that you were able to render the API docstrings using this workflow. Could you check if there any difference between your forked fourigui and `main`?

https://github.com/diffpy/diffpy.fourigui/actions/runs/12209252446

Screenshot 2024-12-06 at 9 50 55 PM

**Comment by sbillinge** [comment]
Could this be the problem maybe?:
```
WARNING: autodoc: failed to import module 'fourigui' from module 'diffpy.fourigui'; the following exception was raised:
Cannot load backend 'tkagg' which requires the 'tk' interactive framework, as 'headless' is currently running [autodoc.import_object]
```

**Comment by sbillinge** [comment]
Maybe we can't build the documentation headless, or we need another workaround?  Pls could you look into it?

**Comment by cadenmyers13** [comment]
@sbillinge Where does this warning come from? Im not getting this warning when i build on my end. I'd like to reproduce locally.

**Comment by sbillinge** [comment]
That was in the log in the action called docs and then under build documentation.  I am not sure what the problem is (and it could be happening at the deploy stage) but I just noticed that error.  I don't know if it is the problem.  Look here:
https://github.com/diffpy/diffpy.fourigui/actions/runs/12209241804/job/34063721050

**Comment by bobleesj** [comment]
https://github.com/diffpy/diffpy.fourigui/pull/73

Please see this new PR, fixing this problem.

**Pull request merged**
