### PR TITLE
add tutorial to documentation

### PR DESCRIPTION
**Pull request by cadenmyers13**

### CODE REVIEW

**Review by sbillinge — COMMENTED** [review]
I think tutorial is not part of the API so I am not sure what is going on here. Please can you post an image of the front page of the built docs and we can decide what it should look like

**Comment by cadenmyers13** [comment]
> I think tutorial is not part of the API so I am not sure what is going on here. Please can you post an image of the front page of the built docs and we can decide what it should look like

I copied the format from `pdfgui`. Here's a screenshot of `index.html` from both.

Screenshot 2024-10-27 at 3 57 53 PM
Screenshot 2024-10-27 at 3 57 25 PM

**Comment by sbillinge** [comment]
ok, this looks good.  I would just put it above the license and release notes, as it is in PDFgui.  Then I can merge it.

**Comment by cadenmyers13** [comment]
@sbillinge done

**Pull request merged**
