### PR TITLE
Surpress RuntimeWarning in test

### PR DESCRIPTION
**Pull request by cadenmyers13**
See comment on [other PR](https://github.com/diffpy/diffpy.fourigui/pull/38#issuecomment-2440188128)

### CODE REVIEW

**Comment by sbillinge** [comment]
@cadenmyers13 please see the discussion on the other PR.  I will close this for now as I am guessing it is not what we want.

**Comment by cadenmyers13** [comment]
> @cadenmyers13 please see the discussion on the other PR. I will close this for now as I am guessing it is not what we want.

@sbillinge In reference to [your message here](https://github.com/diffpy/diffpy.fourigui/pull/45#issuecomment-2443230963), is this PR what you want? The edits made here surpress the Runtimewarnings.

**Comment by sbillinge** [comment]
> > @cadenmyers13 please see the discussion on the other PR. I will close this for now as I am guessing it is not what we want.
> 
> @sbillinge In reference to [your message here](https://github.com/diffpy/diffpy.fourigui/pull/45#issuecomment-2443230963), is this PR what you want? The edits made here surpress the Runtimewarnings.

yes, if this works, this is exactly what I am after....  code is good, tests are testing what we want, code generates appropriate warnings, but they don't appear as warnings in the tests.....perfect if this actually does suppress them (I guess you tested that?)

**Comment by cadenmyers13** [comment]
> > > @cadenmyers13 please see the discussion on the other PR. I will close this for now as I am guessing it is not what we want.
> 
> > 
> 
> > @sbillinge In reference to [your message here](https://github.com/diffpy/diffpy.fourigui/pull/45#issuecomment-2443230963), is this PR what you want? The edits made here surpress the Runtimewarnings.
> 
> 
> 
> yes, if this works, this is exactly what I am after....  code is good, tests are testing what we want, code generates appropriate warnings, but they don't appear as warnings in the tests.....perfect if this actually does suppress them (I guess you tested that?)

Yes, running pytest I did not get the RuntimeWarning

**Comment by bobleesj** [comment]
@cadenmyers13 just a thought, do we want to a bit documentation/comments in the test code itself why those warnings are being surpassed for future members?

**Comment by sbillinge** [comment]
Nice @cadenmyers13 !  Code is now just a little bit better.

**Comment by cadenmyers13** [comment]
> @cadenmyers13 just a thought, do we want to a bit documentation/comments in the test code itself why those warnings are being surpassed for future members?

Good idea. I can add that

**Pull request merged**
